config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'conversions#new'
  resources :conversions, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversion.rb
class Conversion < ApplicationRecord
  belongs_to :user
  validates :from_currency, presence: true
  validates :to_currency, presence: true
  validates :amount, numericality: true, presence: true
  validate :custom_validations

  private

  def custom_validations
    errors.add(:to_currency, "can't be same") if from_currency == to_currency
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
  require 'date'
  require 'money/bank/currencylayer_bank'
  def index
    @conversions = Conversion.where(user: current_user)
  end

  def new
    @conversion = Conversion.new
  end

  def create
    @conversion = Conversion.new(strong_params)
    @conversion.user = current_user
    @conversion.date = Date.today
    @conversion.result = convertion(@conversion.amount, @conversion.from_currency, @conversion.to_currency)
    @conversion.save ? (redirect_to new_conversion_path) : (render :new)
  end

  def destroy
    @conversion = Conversion.find(params[:id])
    @conversion.destroy
    redirect_to conversions_path
  end

  private

  def strong_params
    params.require(:conversion).permit(:from_currency, :to_currency, :amount)
  end

  def convertion(amount, from, to)
    return nil if amount.class == String || amount.nil?

    mclb = Money::Bank::CurrencylayerBank.new
    mclb.access_key = ENV["CURRENCY_TOKEN"]
    mclb.update_rates
    rate = mclb.get_rate(from, to)
    (amount * rate)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversions/index.html.erb
<% if @conversions.present? %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Amount</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
        <th scope="col">Result</th>
        <th scope="col">Date</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @conversions.reverse.each_with_index do |conversion, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= conversion.amount.round(2) %></td>
          <td><%= conversion.from_currency %></td>
          <td><%= conversion.to_currency %></td>
          <td><%= conversion.result.round(2) %></td>
          <td><%= l(conversion.date, format: :long) %></td>
          <td><%= link_to '', conversion_path(conversion), class: "fa fa-trash trash-icon text-danger", method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1 class="d-flex justify-content-center">You don't have any conversions yet.</h1>
<% end %>

app/views/conversions/new.html.erb
<div class="container d-flex flex-column align-items-center justify-content-center">
  <div class="converter">
    <div class="first-part d-flex my-3 justify-content-center">
    <% @conversions = Conversion.where(user: current_user) || [] %>
      <%= simple_form_for @conversion do |f| %>
        <%= f.input :amount, label: false, required: true, as: :text, input_html: { class: 'amount', value: (@conversions.empty?)? 0 : @conversions.last.amount.round(2) } %>
        <div class="d-flex justify-content-center">
          <%= f.input :from_currency, label: false, collection: ['USD', 'EUR', 'CHF'], selected: (@conversions.empty?)? 'USD' : @conversions.last.from_currency, input_html: { class: 'currency' }, include_blank: false %>
        </div>
        <div class="small-3 columns">
          <%= button_tag type: 'submit', class: "button postfix border-0 button-mine" do %>
            <i class="fas fa-arrow-circle-down" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="d-flex justify-content-center my-3">
          <%= f.input :to_currency, label: false, collection: ['EUR', 'CHF','USD'], selected: (@conversions.empty?)? 'EUR' : @conversions.last.to_currency, input_html: { class: 'currency'}, include_blank: false %>
        </div>
      <% end %>
    </div>
    <div class="second-part">
      <p class="result"><%= (@conversions.empty?)? 0 : @conversions.last.result.round(2) %></p>
    </div>
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyConverter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "HISTORY", conversions_path, class: "btn-primary rounded-pill btn-convrt text-white font-weight-bold nav-link mr-5 px-3" %>
        </li>
        <li class="nav-item active">
          <%= link_to "CONVERTER", new_conversion_path, class: "btn-primary rounded-pill btn-convrt text-white font-weight-bold nav-link mr-5 px-3" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars3.githubusercontent.com/u/68437832?s=400&u=4b5b8715955ad97f7c60e359cc2d2c2b4a800fe8&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>